In [12]:
import os
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

The ABC dataset originally has 23 stories x 2 voices = 46 audio clips (see https://github.com/NickRiccardi/ABC_neuroimaging)

In [18]:
Dir_audio = r'X:\PROJECTS\ABC@UofSC\3-Experiments\Affective_narrative\Audio_normalized\Normalized\English_language'
df_master = pd.DataFrame({'audio':os.listdir(Dir_audio)})
df_master[['voice','story']] = df_master['audio'].str.split('_',1,expand=True)
df_master['story'] = df_master.story.str.replace('.wav','')
df_master.head()

                              audio    voice                 story
0            Allison_AgedMother.wav  Allison            AgedMother
1         Allison_BiggestWastes.wav  Allison         BiggestWastes
2       Allison_BulliesPronouns.wav  Allison       BulliesPronouns
3  Allison_BulliesRepeatedNames.wav  Allison  BulliesRepeatedNames
4     Allison_MetaphorsPronouns.wav  Allison     MetaphorsPronouns

The story transcripts were segmented by two RAs

In [30]:
Dir_SegLabels = r'X:\PROJECTS\ABC@UofSC\3-Experiments\Affective_narrative\behavioral\segmentation_audacity\output\segmentation_labels'
Dir_transcript = r'X:\PROJECTS\ABC@UofSC\3-Experiments\Affective_narrative\behavioral\segmentation_audacity\output\segmentation_transcript'
for i, row in df_master.iterrows():
    # Segment Labels
    filename = os.path.join(Dir_SegLabels,f"{row['voice']}_{row['story']}_labels.txt")
    if os.path.exists(filename):
        df_master.loc[i,'SegLabel'] = 'Done'

    # Transcripts
    filename = os.path.join(Dir_transcript,f"{row['story']}_transcript_finished.docx")
    if os.path.exists(filename):
        df_master.loc[i,'SegTranscript'] = 'Done'
df_master.loc[df_master['SegTranscript'].isna()]

,audio,voice,story,SegLabel,SegTranscript
6,Brandi_Aqua.wav,Brandi,Aqua,NaN,NaN
9,Brandi_EmotionSentences_953.wav,Brandi,EmotionSentences_953,NaN,NaN
10,Brandi_EmpireState.wav,Brandi,EmpireState,Done,NaN
21,Jack_EmotionSentences_953.wav,Jack,EmotionSentences_953,NaN,NaN
28,Jacob_Aqua.wav,Jacob,Aqua,NaN,NaN
30,Jacob_EmpireState.wav,Jacob,EmpireState,Done,NaN
32,Jacob_FireSelected.wav,Jacob,FireSelected,Done,NaN
42,WavenetB_IronyParas.wav,WavenetB,IronyParas,NaN,NaN
43,WavenetF_FireSelected.wav,WavenetF,FireSelected,Done,NaN
44,WavenetF_IronyParas.wav,WavenetF,IronyParas,NaN,NaN

In [28]:
row['story'] = 
filename = os.path.join(Dir_transcript,f"{row['story']}_transcript_finished.docx")

,audio,voice,story,SegLabel
0,Allison_AgedMother.wav,Allison,AgedMother,Done
1,Allison_BiggestWastes.wav,Allison,BiggestWastes,Done
2,Allison_BulliesPronouns.wav,Allison,BulliesPronouns,Done
3,Allison_BulliesRepeatedNames.wav,Allison,BulliesRepeatedNames,Done
4,Allison_MetaphorsPronouns.wav,Allison,MetaphorsPronouns,Done
5,Allison_MetaphorsRepeatedNames.wav,Allison,MetaphorsRepeatedNames,Done
6,Brandi_Aqua.wav,Brandi,Aqua,NaN
7,Brandi_BradfordBoar.wav,Brandi,BradfordBoar,Done
8,Brandi_Elvis.wav,Brandi,Elvis,Done
9,Brandi_EmotionSentences_953.wav,Brandi,EmotionSentences_953,NaN
10,Brandi_EmpireState.wav,Brandi,EmpireState,Done
11,Brandi_FairyTree.wav,Brandi,FairyTree,Done
12,Brandi_FirstConcert.wav,Brandi,FirstConcert,Done
13,Brandi_HappyDay.wav,Brandi,HappyDay,Done
14,Brandi_HowCouldYou.wav,Brandi,HowCouldYou,Done
15,Brandi_Roswell.wav,Brandi,Roswell,Done
16,Brandi_TaleofTwoCountries.wav,Brandi,TaleofTwoCountries,Done
17,Brandi_TigerandLion.wav,Brandi,TigerandLion,NaN
18,Brandi_UserFriendly.wav,Brandi,UserFriendly,Done
19,Jack_BiggestWastes.wav,Jack,BiggestWastes,Done
20,Jack_Elvis.wav,Jack,Elvis,Done
21,Jack_EmotionSentences_953.wav,Jack,EmotionSentences_953,NaN
22,Jack_FirstConcert.wav,Jack,FirstConcert,Done
23,Jack_MetaphorsPronouns.wav,Jack,MetaphorsPronouns,Done
24,Jack_MetaphorsRepeatedNames.wav,Jack,MetaphorsRepeatedNames,Done
25,Jack_ProfessionalDecline.wav,Jack,ProfessionalDecline,Done
26,Jack_Roswell.wav,Jack,Roswell,Done
27,Jacob_AgedMother.wav,Jacob,AgedMother,Done
28,Jacob_Aqua.wav,Jacob,Aqua,NaN
29,Jacob_BradfordBoar.wav,Jacob,BradfordBoar,Done
30,Jacob_EmpireState.wav,Jacob,EmpireState,Done
31,Jacob_FairyTree.wav,Jacob,FairyTree,Done
32,Jacob_FireSelected.wav,Jacob,FireSelected,Done
33,Jacob_HappyDay.wav,Jacob,HappyDay,Done
34,Jacob_HowCouldYou.wav,Jacob,HowCouldYou,Done
35,Jacob_Koko.wav,Jacob,Koko,Done
36,Jacob_TaleofTwoCountries.wav,Jacob,TaleofTwoCountries,Done
37,Jacob_TigerandLion.wav,Jacob,TigerandLion,Done
38,Jacob_UserFriendly.wav,Jacob,UserFriendly,Done
39,Jewell_ProfessionalDecline.wav,Jewell,ProfessionalDecline,Done
40,WavenetB_BulliesPronoun.wav,WavenetB,BulliesPronoun,Done
41,WavenetB_BulliesRepeatedNames.wav,WavenetB,BulliesRepeatedNames,Done
42,WavenetB_IronyParas.wav,WavenetB,IronyParas,NaN
43,WavenetF_FireSelected.wav,WavenetF,FireSelected,Done
44,WavenetF_IronyParas.wav,WavenetF,IronyParas,NaN
45,WavenetF_Koko.wav,WavenetF,Koko,Done