In [2]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json
import shutil
Dir_github = '/work/desai-lab/xuanyang/Project/ABC/github'
Dir_dataset = '/work/desai-lab/ABC_dataset'
Dir_preprocess = os.path.join(Dir_dataset,'derivatives','fmriprep')

In [41]:
df_master = pd.read_csv(os.path.join(Dir_github,'derivatives','test_Fam','df_master_Fam120.csv'))
# dfs_eprime = pd.read_csv(os.path.join(Dir_github,'derivatives','test_Fam','dfs_eprime_Fam_by1361.csv'))
df_master

,subid,visit,Fam_fmri,Fam_eprime,age,sex,trans_x,trans_y,trans_z,rot_x,rot_y,rot_z,motion_max
0,1005,1.0,1.0,1.0,65.0,2.0,0.041617,0.267869,0.463099,0.007059,0.003916,0.003123,0.463099
1,1007,1.0,1.0,1.0,69.0,2.0,0.383059,0.671302,0.386057,0.009304,0.001248,0.003724,0.671302
2,1008,1.0,1.0,1.0,77.0,2.0,0.075486,0.203145,0.118612,0.005849,0.000214,0.001656,0.203145
3,1009,1.0,1.0,1.0,75.0,2.0,0.000065,0.349682,0.215196,0.003958,0.000177,0.000196,0.349682
4,1018,1.0,1.0,1.0,60.0,2.0,0.026452,0.412780,0.433625,0.003764,0.005943,0.000393,0.433625
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1302,1.0,1.0,1.0,23.0,1.0,0.565818,0.318678,0.295166,0.004322,0.001432,0.012690,0.565818
116,1305,1.0,1.0,1.0,61.0,2.0,0.061026,0.375817,0.324899,0.005508,0.000556,0.000923,0.375817
117,1306,1.0,1.0,1.0,28.0,2.0,0.485715,0.411004,0.707648,0.018751,0.001389,0.016267,0.707648
118,1311,1.0,1.0,1.0,20.0,2.0,0.174499,0.285192,0.111143,0.003649,0.008804,0.005942,0.285192
119,1323,1.0,1.0,1.0,70.0,2.0,0.187637,0.683567,0.638828,0.014991,0.009570,0.000711,0.683567

In [42]:
nWM = 5
nCSF = 5
nPolort = 2
nMotion = 6
censor = 1


contrast = 'BtnPrs'
pipeline_clean = f"test_Fam_mot{nMotion}csf{nCSF}wm{nWM}plt{nPolort}cen{censor}"
pipeline = f"{pipeline_clean}_{contrast}"

Dir_clean = os.path.join(Dir_github,'derivatives',pipeline_clean)
Dir_pipeline = os.path.join(Dir_github,'derivatives',pipeline)
if not os.path.exists(os.path.join(Dir_pipeline,'results','secondlevel')):
#     os.makedirs(Dir_pipeline)
    os.makedirs(os.path.join(Dir_pipeline,'results','secondlevel'))
pipeline

'test_Fam_mot6csf5wm5plt2cen1_BtnPrs'

# Bad subjects

In [46]:
Dir_firstlevel = os.path.join(Dir_pipeline,'results','firstlevel')
Dir_secondlevel = os.path.join(Dir_pipeline,'results','secondlevel')
df_master['cplt'] = 0
df_master['statImg'] = ''
for i, row in df_master.iterrows():
    subid = int(row['subid'])
    visit = int(row['visit'])
    Dir_subject = os.path.join(Dir_pipeline,'results','firstlevel',f"sub-{subid}",f"sub-{subid}.results")
#     Dir_output = os.path.join(Dir_pipeline,'results','firstlevel',f'sub-{subid}')
    img = os.path.join(Dir_subject,f'stats.sub-{subid}_REML+tlrc.BRIK')
    if os.path.exists(img):
        df_master.loc[i,'cplt'] = 1
        df_master.loc[i,'statImg'] = img
df_master_ana = df_master.loc[df_master['cplt']==1]
df_master_ana

,subid,visit,Fam_fmri,Fam_eprime,age,sex,trans_x,trans_y,trans_z,rot_x,rot_y,rot_z,motion_max,cplt,statImg
0,1005,1.0,1.0,1.0,65.0,2.0,0.041617,0.267869,0.463099,0.007059,0.003916,0.003123,0.463099,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
1,1007,1.0,1.0,1.0,69.0,2.0,0.383059,0.671302,0.386057,0.009304,0.001248,0.003724,0.671302,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
2,1008,1.0,1.0,1.0,77.0,2.0,0.075486,0.203145,0.118612,0.005849,0.000214,0.001656,0.203145,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
3,1009,1.0,1.0,1.0,75.0,2.0,0.000065,0.349682,0.215196,0.003958,0.000177,0.000196,0.349682,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
4,1018,1.0,1.0,1.0,60.0,2.0,0.026452,0.412780,0.433625,0.003764,0.005943,0.000393,0.433625,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1302,1.0,1.0,1.0,23.0,1.0,0.565818,0.318678,0.295166,0.004322,0.001432,0.012690,0.565818,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
116,1305,1.0,1.0,1.0,61.0,2.0,0.061026,0.375817,0.324899,0.005508,0.000556,0.000923,0.375817,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
117,1306,1.0,1.0,1.0,28.0,2.0,0.485715,0.411004,0.707648,0.018751,0.001389,0.016267,0.707648,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
118,1311,1.0,1.0,1.0,20.0,2.0,0.174499,0.285192,0.111143,0.003649,0.008804,0.005942,0.285192,1,/work/desai-lab/xuanyang/Project/ABC/github/de...
119,1323,1.0,1.0,1.0,70.0,2.0,0.187637,0.683567,0.638828,0.014991,0.009570,0.000711,0.683567,1,/work/desai-lab/xuanyang/Project/ABC/github/de...

In [23]:
import subprocess
import pandas as pd

def get_subbricks_info(dataset):
    # Run 3dinfo command
    result = subprocess.run(['/work/apps/AFNI/linux_openmp_64/3dinfo', '-verb', dataset], capture_output=True, text=True)
    lines = result.stdout.split('\n')
    
    # Extract lines with sub-brick info
    subbrick_lines = [line for line in lines if "sub-brick" in line]
    
    # Extract indices and names from those lines
    subbricks = []
    for line in subbrick_lines:
        idx = int(line.split('#')[1].split()[0])
        name = line.split("'")[1]
        subbricks.append((idx, name))
        
    return subbricks

In [37]:

df_subbricks = pd.DataFrame(get_subbricks_info(df_master_ana.statImg[0]),columns=['imgID', 'regName'])
df_regModel = df_subbricks.loc[df_subbricks['imgID'].isin([7,10])].copy()
# df_regModel['contrast'] = df_regModel['regName'].str.replace('#0_Coef','')
df_regModel['contrast'] = ['btnprs','word_pic']
df_regModel

    imgID          regName  contrast
7       7       btn#0_Coef    btnprs
10     10  word_pic#0_Coef  word_pic

# Unthreshold

In [45]:
threshold = 'unthreshold'
for i,row in df_regModel.iterrows():
    contrast = row['contrast']
    imgID = row['imgID']
    
    Dir_output = os.path.join(Dir_secondlevel,contrast,threshold)
    if not os.path.exists(Dir_output):
        os.makedirs(Dir_output)
                               
                               
    os.chdir(Dir_output)
    scriptFile = os.path.join(Dir_output,'secondlevel_'+contrast)
    with open(scriptFile, "w") as f:
        f.write("#!/bin/tcsh -xef \n")
        f.write(f"/work/apps/AFNI/linux_openmp_64/3dttest++ -prefix {contrast} \\\n")
#         f.write("-mask {} \\\n".format(groupMask))
#             f.write("-ClustSim -seed 31415 \\\n")
        f.write(f"-setA {contrast} \\\n")
        for i,statImg in enumerate(df_master_ana['statImg']):
            
            f.write(f"{i:02} {statImg.replace('.BRIK','')}'[{str(imgID)}]' \\\n")
#             f.write(f'/work/apps/AFNI/linux_openmp_64/3dAFNItoNIFTI {df_regModel.regName.values[0]}+tlrc.BRIK"[1]" -prefix {df_regModel.regName.values[0]}.nii')
#     os.chdir(Dir_output)
    subprocess.run(f"tcsh {scriptFile}",shell=True)

++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 112 volumes corresponding to option '-setA'
++ no mask ==> processing all 1082035 voxels
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 77245 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 77245 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 btnprs_Tstat] = 2.21653e-07
 + Added 1 FDR curve to dataset
++ Output dataset ./btnprs+tlrc.BRIK
++ ----- 3dttest++ says so long, farewell, and happy trails to you :) -----
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 112 volumes corresponding to option '-setA'
++ no mask ==> processing all 1082035 voxels
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 77245 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 77245 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 word_pic_Tstat] = 5.09558e-13
 + Added 1 FDR curve to dataset
++ Output dataset ./word_pic+tlrc.BRIK
++ ----- 3dttest++ says so long, farewell, and happy trails to you :) -----