In [2]:
# pip install openai --upgrade
import os
import pandas as pd
import warnings
import json
import random
import numpy as np
warnings.simplefilter(action='ignore', category=FutureWarning)

In [4]:
# Dir_github = r'X:\PROJECTS\ABC@UofSC\3-Experiments\NSF_valence\github'
Dir_github = r'/work/xy6/Project/ABC/github/'
repo = 'ABC_valence'
pipeline = 'getRatings_GPT'
Dir_working = os.path.join(Dir_github,repo,'scripts','Behavioral',pipeline)
Dir_results = os.path.join(Dir_github,'derivatives','behavioral','ratings','gpt')
Dir_instruct = os.path.join(Dir_working,'instructions')
Dir_segments = os.path.join(Dir_github,'derivatives','behavioral','segmentation')
df_story = pd.DataFrame({'story':[x for x in os.listdir(Dir_segments) if '_formatted.csv' in x ]})
df_story['story'] = df_story['story'].str.split('_',expand=True)[1]

for i,row in df_story.iterrows():
    df_tmp = pd.read_csv(os.path.join(Dir_segments,f"segment_{row['story']}_formatted.csv"))
    df_story.loc[i,'N_segments'] = df_tmp.shape[0]
df_story.head()

          story  N_segments
0  FirstConcert       118.0
1   HowCouldYou       124.0
2      Rosewell       119.0
3          Koko        94.0
4  TigerandLion       135.0

In [15]:
def get_rating_gpt(Dir_ratings):
    List_models = [x for x in os.listdir(os.path.join(Dir_ratings,'gpt')) if 'gpt' in x]
    for model in List_models:
        List_files = os.listdir(os.path.join(Dir_ratings,'gpt',model))
        List_files = [x for x in List_files if 'rating' in x]
        for file in List_files:
            df = pd.read_csv(os.path.join(Dir_ratings,'gpt',model,file))

    return(df)

In [16]:
Dir_ratings = os.path.join(Dir_github,'derivatives','behavioral','ratings',)
List_models = get_rating_gpt(Dir_ratings)
List_models

,segment,reason,story,idx,audio,segment_raw,onset,offset,words,idx_raw,text,raw,V,A,firstlast,firstword,lastword,flag,iteration
0,"Long, long ago",positioning element,AgedMother,1,Jacob_AgedMother,"Long, long ago",5.200000,6.36,Long|long|ago,0,"#####1 Long, long ago#####\n",1 Long ago 0 2,0.0,2.0,Long ago,Long,ago,11,0
1,there lived at the foot of the mountain,positioning element,AgedMother,2,Jacob_AgedMother,there lived at the foot of the mountain,6.650000,8.29,there|lived|at|the|foot|of|the|mountain,1,#####2 there lived at the foot of the mountain...,2 there mountain 1 3,1.0,3.0,there mountain,there,mountain,11,0
2,"a poor farmer and his aged, widowed mother",>maximal segment,AgedMother,3,Jacob_AgedMother,"a poor farmer and his aged, widowed mother.",8.309999,11.07,a|poor|farmer|and|his|aged|widowed|mother,2,"#####3 a poor farmer and his aged, widowed mot...",3 a mother -1 4,-1.0,4.0,a mother,a,mother,11,0
3,They owned a bit of land,-,AgedMother,4,Jacob_AgedMother,They owned a bit of land,12.080000,13.30,They|owned|a|bit|of|land,3,#####4 They owned a bit of land#####\n,4 They land 1 3,1.0,3.0,They land,They,land,11,0
4,which supplied them with food,relative clause,AgedMother,5,Jacob_AgedMother,"which supplied them with food,",13.309999,14.79,which|supplied|them|with|food,4,#####5 which supplied them with food#####\n,5 which food 2 3,2.0,3.0,which food,which,food,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18983,to help us in everyday life,infinitival phrase,UserFriendly,134,Jacob_UserFriendly,"to help us in everyday life,",350.349999,352.08,to|help|us|in|everyday|life,133,#####134 to help us in everyday life#####\n,134 to life 2 3,2.0,3.0,to life,to,life,11,9
18984,"to carry our packages, provide a way to sit wh...",infinitival phrase,UserFriendly,135,Jacob_UserFriendly,"to carry our packages, provide a way to sit wh...",352.150000,357.66,to|carry|our|packages|provide|a|way|to|sit|whe...,134,"#####135 to carry our packages, provide a way ...",135 to event 1 3,1.0,3.0,to event,to,event,11,9
18985,"and yes, to maintain our balance",conjunction; >maximal segment,UserFriendly,136,Jacob_UserFriendly,"and yes, to maintain our balance?",357.770000,359.81,and|yes|to|maintain|our|balance,135,"#####136 and yes, to maintain our balance#####\n","136 and yes, 1 3",NaN,NaN,"and yes,",and,"yes,",10,9
18986,"Make them items of pride, stylish enough",-,UserFriendly,137,Jacob_UserFriendly,"Make them items of pride, stylish enough",359.809999,NaN,Make|them|items|of|pride|stylish|enough,136,"#####137 Make them items of pride, stylish eno...",137 Make them 2 4,NaN,NaN,Make them,Make,them,10,9
18987,that everyone will want one,relative clause; >maximal segment,UserFriendly,138,Jacob_UserFriendly,that everyone will want one.,NaN,NaN,that|everyone|will|want|one,137,#####138 that everyone will want one#####\n,138 that one 2 4,2.0,4.0,that one,that,one,11,9